defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: true
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction:
    - maximize
    - maximize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 3
    params:
      beta: tag(log, interval(1e-3, 1))
      bernoulli_p: range(0.2, 0.90, step=0.1)
      # seed: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
      # embedding_dim: choice(32, 64, 128, 256)
      # num_heads: choice(1, 2, 4, 8)
      # batch_size: choice(64, 128, 256)
      # lr: tag(log, interval(1e-5, 1e-3))
      # gamma: tag(log, interval(0.9, 0.999))
      # exploration_fraction: range(0.1, 0.5, step=0.1)
      # exploration_initial_eps: range(0.5, 1.0, step=0.1)
      # exploration_final_eps: range(0.05, 0.2, step=0.05)
      # fraction_best: range(0.1, 0.8, step=0.1)
      # tau: tag(log, interval(0.001, 1))
seed: 42
gamma: 0.99
learning_starts: 0
gradient_steps: 1
exploration_fraction: 0.4
exploration_initial_eps: 1.0
exploration_final_eps: 0
buffer_size: 500000
fraction_best: 0.4
tau: 0.055
embedding_dim: 64
num_heads: 8
batch_size: 256
lr: 0.00095
cql_alpha: 0.1
beta: 0.003
bernoulli_p: 0.5
# eta: 0.1
# prior_scale: 0.1

# agent_type should be from (bc, dqn, dsac, ensemble)
# integration type should be from (var, min, rem)
agent_type: ensemble
integration_type: var
bootstrapping: true
diversification: false
with_prior: false

# if true, simulate a failure by raising an exception
error: false

group_name: beta_bernoulli_p_opt_5
var_to_include: bernoulli_p

upper_percentile: 100
sample_fraction: 0.05