# defaults:
  # - override hydra/sweeper: optuna
#   - override hydra/sweeper/sampler: tpe

defaults:
  - _self_  
  - override hydra/launcher: joblib 

# hydra:
  # sweeper:
  #   sampler:
  #     _target_: optuna.samplers.TPESampler
  #     seed: 123
  #     consider_prior: true
  #     prior_weight: 1.0
  #     consider_magic_clip: true
  #     consider_endpoints: false
  #     n_startup_trials: 10
  #     n_ei_candidates: 24
  #     multivariate: true
  #     warn_independent_sampling: true
  #   _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  #   direction:
  #   - maximize
  #   - maximize
  #   study_name: sphere
  #   storage: null
  #   n_trials: 50
  #   n_jobs: 1
  #   params:
  #     seed: 1, 2, 3, 4, 5
      # embedding_dim: choice(32, 64, 128, 256)
      # num_heads: choice(1, 2, 4, 8)
      # batch_size: choice(64, 128, 256)
      # lr: tag(log, interval(1e-5, 1e-3))
      # gamma: tag(log, interval(0.9, 0.999))
      # hard_update_freq: range(250, 2000, step=250)
# Note: To run multiple seeds just comment everything above
seed: 42
gpu_id: 5
gamma: 1
learning_starts: 0
gradient_steps: 1
exploration_fraction: 0.4
exploration_initial_eps: 1.0
exploration_final_eps: 0
buffer_size: 500000
fraction_best: 0.4
tau: 0.055
embedding_dim: 64
num_heads: 8
batch_size: 256
lr: 0.00095
hard_update_freq: 1000
n_members: 5
bernoulli_p: 0.9
prior_scale: 0.8
eta: 0.9
theta: 1

# if true, simulate a failure by raising an exception
error: false

var_to_include: seed
agent_type: sac_ensemble
integration_type: var

bootstrapping: false
with_prior: false
diversification: false

n_episodes: 15000
group_name: sac_ensemble_trials
upper_percentile: 100
sample_fraction: 0.05
beta: 0